import {
  X,
  Sparkles,
  CheckCircle,
  AlertTriangle,
  Mail,
  MapPin,
  Briefcase,
  GraduationCap,
} from "lucide-react";

interface Candidate {
  id: string;
  name: string;
  title: string;
  company: string;
  experienceYears: number;
  location: string;
  imageUrl: string;
  about: string;
  workExperience: {
    company: string;
    role: string;
    years: number;
  }[];
  education: {
    degree: string;
    institution: string;
  }[];
  matchMeta: {
    score: number;
    strengths: string[];
    gaps: string[];
  };
  availability: string;
}

interface CandidateDrawerProps {
  open: boolean;
  candidate: Candidate | null;
  onClose: () => void;
}

export default function CandidateDrawer({
  open,
  candidate,
  onClose,
}: CandidateDrawerProps) {
  if (!open || !candidate) return null;

  return (
    <div className="fixed inset-0 z-50 flex">
      {/* Overlay */}
      <div
        className="absolute inset-0 bg-black/40 backdrop-blur-sm"
        onClick={onClose}
      />

      {/* Drawer */}
      <aside className="ml-auto w-full sm:w-[420px] bg-white h-full shadow-xl flex flex-col z-50">
        {/* Header */}
        <div className="px-6 py-4 border-b flex items-center justify-between">
          <div>
            <h2 className="text-lg font-bold text-slate-900">
              AI Candidate Insight
            </h2>
            <p className="text-xs text-slate-500">
              Generated by SARAL AI
            </p>
          </div>
          <button onClick={onClose}>
            <X className="w-5 h-5 text-slate-500" />
          </button>
        </div>

        {/* Content */}
        <div className="flex-1 overflow-y-auto px-6 py-6 space-y-6">
          {/* ===== PROFILE HEADER ===== */}
          <div className="flex items-center gap-4">
            <div className="w-12 h-12 rounded-full bg-indigo-100 text-indigo-600 flex items-center justify-center text-xl font-semibold">
                {candidate?.name?.[0]?.toUpperCase() || "C"}
            </div>

            <div>
              <h3 className="text-lg font-semibold text-slate-900">
                {candidate.name}
              </h3>
              <p className="text-sm text-slate-600">
                {candidate.title} • {candidate.company}
              </p>
              <div className="flex items-center gap-3 text-xs text-slate-500 mt-1">
                <span className="flex items-center gap-1">
                  <MapPin className="w-3 h-3" />
                  {candidate.location}
                </span>
                <span className="flex items-center gap-1">
                  <Briefcase className="w-3 h-3" />
                  {candidate.experienceYears}+ yrs
                </span>
              </div>
            </div>
          </div>

          {/* ===== AI MATCH ===== */}
          <div className="bg-indigo-50 border border-indigo-100 rounded-2xl p-5">
            <div className="flex items-center gap-3 mb-3">
              <Sparkles className="w-5 h-5 text-indigo-600" />
              <p className="text-sm font-semibold text-indigo-700">
                AI Match Score
              </p>
            </div>

            <p className="text-4xl font-bold text-indigo-600 mb-2">
              {candidate.matchMeta.score}%
            </p>

            <p className="text-sm text-indigo-700">
              Strong alignment based on skills, experience, and role fit.
            </p>
          </div>

          {/* ===== ABOUT ===== */}
          <div>
            <h4 className="text-sm font-semibold text-slate-900 mb-2">
              Summary
            </h4>
            <p className="text-sm text-slate-600">
              {candidate.about}
            </p>
          </div>

          {/* ===== STRENGTHS ===== */}
          <div>
            <h4 className="text-sm font-semibold text-slate-900 mb-3">
              Strengths identified by AI
            </h4>

            <ul className="flex flex-wrap gap-2">
              {candidate.matchMeta.strengths.map((skill) => (
                <li
                  key={skill}
                  className="flex items-center gap-1.5
                             text-xs font-medium text-green-700
                             bg-green-50 px-3 py-1 rounded-full"
                >
                  <CheckCircle className="w-3 h-3" />
                  {skill}
                </li>
              ))}
            </ul>
          </div>

          {/* ===== GAPS ===== */}
          <div>
            <h4 className="text-sm font-semibold text-slate-900 mb-3">
              Potential gaps
            </h4>

            <ul className="flex flex-wrap gap-2">
              {candidate.matchMeta.gaps.map((gap) => (
                <li
                  key={gap}
                  className="flex items-center gap-1.5
                             text-xs font-medium text-yellow-700
                             bg-yellow-50 px-3 py-1 rounded-full"
                >
                  <AlertTriangle className="w-3 h-3" />
                  {gap}
                </li>
              ))}
            </ul>
          </div>

          {/* ===== EXPERIENCE ===== */}
          <div>
            <h4 className="text-sm font-semibold text-slate-900 mb-3">
              Work Experience
            </h4>

            <div className="space-y-3">
              {candidate.workExperience.map((exp, i) => (
                <div
                  key={i}
                  className="bg-slate-50 rounded-xl p-3 text-sm"
                >
                  <p className="font-medium text-slate-900">
                    {exp.role}
                  </p>
                  <p className="text-slate-500">
                    {exp.company} • {exp.years} yrs
                  </p>
                </div>
              ))}
            </div>
          </div>

          {/* ===== EDUCATION ===== */}
          <div>
            <h4 className="text-sm font-semibold text-slate-900 mb-3">
              Education
            </h4>

            {candidate.education.map((edu, i) => (
              <div
                key={i}
                className="flex items-center gap-3 text-sm text-slate-600"
              >
                <GraduationCap className="w-4 h-4 text-slate-400" />
                <span>
                  {edu.degree} — {edu.institution}
                </span>
              </div>
            ))}
          </div>

          {/* ===== AVAILABILITY ===== */}
          <div className="bg-slate-50 rounded-xl p-4 text-sm">
            <strong>Availability:</strong>{" "}
            <span className="text-slate-600">
              {candidate.availability}
            </span>
          </div>
        </div>

        {/* Footer Actions */}
        <div className="border-t px-6 py-4 flex gap-3">
          <button className="flex-1 py-2.5 rounded-lg border text-sm font-semibold hover:bg-slate-50">
            Unlock Profile
          </button>
          <button className="flex-1 py-2.5 rounded-lg bg-indigo-600 text-white
                             text-sm font-semibold hover:bg-indigo-700
                             flex items-center justify-center gap-2">
            <Mail className="w-4 h-4" />
            Add to Outreach
          </button>
        </div>
      </aside>
    </div>
  );
}
